/** 학생 play·샌드박스 UI */
export const STUDENT_COPY = {
  phaseOverview: {
    title: "활동 소개",
    description:
      "모둠·역할·모둠 미션을 확인하세요. 전문가 집단에서는 5단계 단서로 맞출 아이템을 추리합니다.",
    placeLabel: "나의 역할",
    missionsSection: "모둠 미션",
    introSection: "활동 안내",
    missionsEmpty: "모둠 미션 정보가 없습니다.",
    requiredItems: (count: number) => `필요 맞출 아이템 ${count}개`,
  },
  phaseExpert: {
    title: "전문가 집단",
    description:
      "같은 역할끼리 모여 단서를 열며 맞출 아이템을 찾으세요. 맞히면 홈 집단으로 돌아가 모둠원에게 알려 주세요.",
    placeLabel: "나의 역할",
    acquiredReturn: "홈 집단으로 돌아가, 맞힌 맞출 아이템을 모둠원에게 설명해 주세요.",
    myItemsSection: "내 맞출 아이템",
    clueSection: "단서 탐색",
    submitSection: "맞출 아이템 제출",
    itemNameLabel: "맞출 아이템 이름",
    itemNamePlaceholder: "단서를 보고 이름을 입력하세요",
    submitButton: "제출하기",
    submitting: "확인 중…",
    acquiredCallout: "맞출 아이템을 찾았어요",
    clueLocked: "앞 단계 단서를 먼저 열어야 볼 수 있어요.",
    clueReveal: "버튼을 누르면 단서가 공개돼요.",
    acquiredBadge: (done: number, total: number) => `${done}/${total} 획득`,
    clueScoreHint: "앞 단계 단서일수록 높은 점수를 받아요.",
    clueCurrentScore: (points: number) => `맞출 아이템 획득 시 +${points}점`,
  },
  phaseHome: {
    title: "홈 집단",
    description:
      "모둠이 모은 맞출 아이템으로 모둠 미션을 해결하세요. 필요한 아이템을 모두 고른 뒤 한 번에 제출합니다.",
    scoreLabel: "모둠 점수",
    pooledItemsSection: "모둠이 모은 맞출 아이템",
    missionsSection: "모둠 미션",
    emptyPool: "아직 모둠이 모은 맞출 아이템이 없어요.",
    emptyPoolHint: "전문가 집단에서 찾은 아이템을 모둠에 공유해 주세요.",
    missionInProgress: "진행 중",
    missionDone: "완료",
    missionChallenging: "도전 중",
    selectItemsHint: "이 모둠 미션에 쓸 맞출 아이템을 골라 주세요.",
    noItemsToSubmit: "제출할 맞출 아이템이 없어요. 먼저 모둠이 아이템을 모아야 해요.",
    submitMission: (count: number) => `선택한 맞출 아이템 ${count}개로 미션 제출`,
    selectItemsButton: "맞출 아이템을 선택해 주세요",
    verifyingMission: "미션 확인 중…",
    finalSection: "최종 제출",
    finalReady: "모둠 미션을 모두 마쳤어요. 최종 결과를 제출해 주세요.",
    finalButton: "최종 결과 제출",
    finalSubmitting: "제출 중…",
    finalDone: "최종 제출 완료",
    finalScore: (score: number) => `모둠 최종 점수: ${score}점`,
    completionBadge: (done: number, total: number) => `${done}/${total} 완료`,
  },
  waiting: {
    headerTitle: "활동 대기",
    headerDescription: "선생님이 수업을 시작할 때까지 기다려 주세요.",
    loadingTitle: "준비 중",
    loadingBody: "활동 안내를 불러오고 있어요.",
    loadingEmoji: "⏳",
    waitingTitle: "곧 활동이 시작됩니다",
    waitingBody1: "시작하면 모둠·역할·맞출 아이템이 배정됩니다.",
    waitingBody2: "배정이 끝나면 같은 모둠끼리 모여 주세요.",
    waitingEmoji: "🧩",
    waitForTeacher: "선생님이 다음 단계로 넘길 때까지 기다려 주세요.",
  },
  intro: {
    timeClue: "제한 시간 안에 모둠 미션을 모두 완료하고 최종 결과를 제출하세요.",
  },
  phaseResults: {
    title: "활동 결과",
    subtitle: "모둠 순위와 나의 기여를 확인하세요.",
    emoji: "🏆",
    groupRankLabel: "모둠 순위",
    groupScoreLabel: "모둠 점수",
    personalRankLabel: "나의 순위",
    personalScoreLabel: "나의 점수",
    emptyMessage: "결과를 불러오지 못했어요. 잠시 후 다시 확인해 주세요.",
    aggregating: "결과 집계 중…",
    groupUnit: "개 모둠",
    personUnit: "명",
  },
} as const;
